#!/bin/sh

set -e
cd `dirname $0`

subdir=`basename $PWD`

export QT_SELECT=5

ALL=moc_all.cpp

echo "// This file is automatically generated by cpp/update-moc.sh" > $ALL

for file in `grep -d skip -l Q_''OBJECT *`; do  #the '' makes grep ignore the script file
	mocfile=`echo $file | awk -F. '{print("moc_"$1".cpp")}'`
	echo "$file -> $mocfile"
	mochack=`sed -n 's,^ *// MOC HACK: \(.*\),\1,p' $file`
#	moc "$file" | sed "$mochack" > $mocfile
	echo "#include \"$subdir/$mocfile\"" >> $ALL
done

for file in `grep -d skip -l 'MOC_''ARCH_DEPENDENT' *`; do    #the '' makes grep ignore the script file
	mocfile32=`echo $file | awk -F. '{print("moc_"$1"_386.cpp")}'`
	mocfile64=`echo $file | awk -F. '{print("moc_"$1"_amd64.cpp")}'`
	echo "$file -> [$mocfile32 || $mocfile64]"
	moc "$file" -D Q_PROCESSOR_X86_32 -o "$mocfile32"
	moc "$file" -D Q_PROCESSOR_X86_64 -o "$mocfile64"
	echo "\n#if __SIZEOF_SIZE_T__ == 4" >> $ALL #|| defined _M_IX86
	echo "#include \"$subdir/$mocfile32\"" >> $ALL
	echo "#elif __SIZEOF_SIZE_T__ == 8" >> $ALL #|| defined _M_AMD64
	echo "#include \"$subdir/$mocfile64\"" >> $ALL
	echo "#else\n#error Your architecture is not supported! (not 32/64 bits)" >> $ALL
	echo "#endif\n" >> $ALL
done